# Path variables
data_path: /ssd_scratch/cvit/kolubex/data
resource_path: /ssd_scratch/cvit/kolubex/data/MovieGraph/resources/
clip_srts_path: /ssd_scratch/cvit/kolubex/data/MovieGraph/srt/clip_srt/
clip_wavlm_feats_path: /ssd_scratch/cvit/kolubex/data/audio/wavlm_feats/
clip_audio_path: /ssd_scratch/cvit/kolubex/data/audios/
emotic_mapping_path: /ssd_scratch/cvit/kolubex/data/emotic_mapping.json
pkl_path: /ssd_scratch/cvit/kolubex/data/MovieGraph/mg/py3loader/
save_path: /ssd_scratch/cvit/kolubex/checkpoints/
save_feats_path: /ssd_scratch/cvit/kolubex/data/
saved_model_path: /ssd_scratch/cvit/kolubex/checkpoints/
hugging_face_cache_path: /ssd_scratch/cvit/kolubex/.cache/
dumps_path: "./dumps"

# Directory names
scene_feat_dir: "_scene_features"
face_feat_dir: "_face_features"
srt_feat_dir: "srt_feats"
audio_feat_dir: "audio_feats"
tracks_dir: "character_tracks"
track_names_dir: "track_names"
track_name_metadata_dir: "track_names/metadata"

# String variables
scene_feat_type: "mvit_v1" # "resnet50_places" # "generic"
face_feat_type: "resnet50_fer" # "emo" # "generic"
srt_feat_type: "independent" # "concat"
audio_feat_type: "total" # "vocals", "no_vocals", "sfx", "music", "total"
srt_feat_model: "roberta"
audio_feat_model: "wavlm"
pkl_name: "all_movies.pkl"

# Boolean variables
use_scene_feats: True
use_char_feats: True
use_srt_feats: True
use_audio_feats: True
get_scene_targets: True
get_char_targets: True
random_feat_selection: True
use_srt_cls_only: True
joint_character_modeling: True
srt_feat_pretrained: False
audio_feat_pretrained: False
use_emotic_mapping: False
shuffle_characters: False

# Numerical variables
model_no: 4.0 # 1.1, 1.2, 2.1, 2.2, 3.0
vid_fps: 23.976023976023978  
max_possible_vid_frame_no: 17500
character_name_selection_threshold: 0.5
target_prediction_threshold: 0.5
top_k: 25 # 10
feat_sampling_rate: 8
num_chars: 4
num_enc_layers: 2
max_feats: 300
max_srt_feats: 300
max_audio_feats: 300
batch_size: 1
num_cpus: 0
epochs: 50
lr: 0.00001
gpu_id: 0
seed: 0

# WandB related variables
wandb:
  logging: False
  project: "emotx_trail" # WandB project name
  entity: "lakshmipathi-balaji" # WandB username
  sweeps: False
  sweep_id: ""
  sweep_run_count: 100
model_name: ''
model_name_suffix: ''

# Static variables (Do not change)
action_feat_group_size: 32
feat_info:
  generic:
    scene_feat_dim: 2048
    face_feat_dim: 512
  emo:
    scene_feat_dim: 512
    face_feat_dim: 4096
  resnet50_places:
    scene_feat_dim: 2048
  resnet50_fer:
    face_feat_dim: 2048
  roberta:
    srt_feat_dim: 768
  mvit_v1:
    scene_feat_dim: 768
  wavlm:
    audio_feat_dim: 512
pos_weight:
  '10': [2.67218201, 2.91079295, 2.36587678, 4.29210134, 3.74098798, 4.70900322, 4.57456829, 4.96806723, 4.72741935, 5.60037175]
  '25': [3.76215098, 4.07158590, 3.36492891, 5.86289121, 5.14819760, 6.40353698, 6.22919937, 6.73949580, 6.42741935, 7.55947955, 8.63389121, 8.3597561, 8.26559356, 9.41855204, 8.39795918, 10.74744898, 11.75623269, 10.09638554, 10.93005181, 12.15714286, 12.62426036, 14.98958333, 12.70535714, 16.18283582, 17.56854839]
  '26': [6.95602606, 7.42241379, 4.56378132, 16.02090592, 41.11206897, 7.46620451, 19.96566524, 15.22923588, 1.61789925, 6.24777448, 38.71544715, 1.90428062, 18.15686275, 4.26400862, 52.09782609, 8.11380597, 1.03202995, 976.0, 1.29342723, 151.65625, 2.56829803, 167.44827586, 44.23148148, 3.28133216, 5.07587065, 6.59720062]

wavlm_finetune:
  kernel_size1: 17
  stride1: 17
  padding1: 1
  conv_type: "avg"
  max_audio_len: 35
  hugging_face_cache_path: /ssd_scratch/cvit/kolubex/.cache/
  lr1: 0.000001
  lr2: 0.00001
  num_wavlm_layers : 3
  lora:
    r : 32
    alpha: 32
    # target_modules : ["model.encoder.layers.%.attention.q_proj", "model.encoder.layers.%.attention.v_proj","model.encoder.layers.%.attention.k_proj"]
    target_modules : "model.encoder.layers.%.attention.k_proj@model.encoder.layers.%.attention.q_proj@model.encoder.layers.%.attention.v_proj"
    dropout: 0.1
    modules_to_save : "head_conv1d@head_linear@head_conv1@head_conv2@head_conv3"
    # modules_to_save : "head_conv1d"
    # layers_pattern : "model.encoder.layers.%.attention.k_proj"
world_size: 3
rank: 0
max_audio_len: 35
wavlm_finetuning: True
original_emotx_version: False
num_wavlm_layers : 3